services:
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
    depends_on:
      - redis
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
